#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os
import sys
import json
import requests
from datetime import datetime
import argparse

# 全局配置
BLOG_BASE_FILE = "blogBase.json"
DOCS_DIR = "docs"
BACKUP_DIR = "backup"
ISSUE_CONTENT_KEY = "content"
PER_PAGE = 2  # 每页显示的文章数量

def init_dirs():
    """初始化必要目录（docs/backup）"""
    for dir_name in [DOCS_DIR, BACKUP_DIR]:
        if not os.path.exists(dir_name):
            os.makedirs(dir_name)
            print(f"✅ 创建目录：{dir_name}")

def load_blog_base():
    """加载博客基础配置（blogBase.json），确保 posts 字段存在"""
    if os.path.exists(BLOG_BASE_FILE):
        try:
            with open(BLOG_BASE_FILE, "r", encoding="utf-8") as f:
                blog_base = json.load(f)
            # 检查并补充缺失的字段
            if "posts" not in blog_base:
                blog_base["posts"] = []
                print("⚠️ 修复配置文件：添加缺失的 posts 字段")
            if "title" not in blog_base:
                blog_base["title"] = "My Gmeek Blog"
            if "subtitle" not in blog_base:
                blog_base["subtitle"] = "Auto-generated by Gmeek"
            if "author" not in blog_base:
                blog_base["author"] = os.getenv("GITHUB_REPOSITORY_OWNER", "Anonymous")
            if "last_update" not in blog_base:
                blog_base["last_update"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            # 保存修复后的配置
            with open(BLOG_BASE_FILE, "w", encoding="utf-8") as f:
                json.dump(blog_base, f, ensure_ascii=False, indent=2)
            return blog_base
        except Exception as e:
            print(f"⚠️ 配置文件格式错误，重新生成默认配置：{str(e)}")
            os.remove(BLOG_BASE_FILE)  # 删除损坏的文件

    # 生成全新的默认配置
    default_base = {
        "title": "My Gmeek Blog",
        "subtitle": "Auto-generated by Gmeek",
        "author": os.getenv("GITHUB_REPOSITORY_OWNER", "Anonymous"),
        "last_update": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "posts": []  # 必含字段，存储文章列表
    }
    with open(BLOG_BASE_FILE, "w", encoding="utf-8") as f:
        json.dump(default_base, f, ensure_ascii=False, indent=2)
    print(f"✅ 生成全新默认配置文件：{BLOG_BASE_FILE}")
    return default_base

def fetch_issue_content(github_token, repo, issue_number):
    """从 GitHub Issue 获取内容（如果指定了 issue_number）"""
    if not issue_number or issue_number == "":
        print("ℹ️ 未指定 Issue 编号，跳过获取 Issue 内容")
        return None
    
    url = f"https://api.github.com/repos/{repo}/issues/{issue_number}"
    headers = {
        "Authorization": f"token {github_token}",
        "Accept": "application/vnd.github.v3+json"
    }
    try:
        response = requests.get(url, headers=headers)
        response.raise_for_status()
        issue = response.json()
        # 返回 Issue 的标题和内容（保留原始Markdown格式）
        return {
            "title": issue["title"],
            "content": issue["body"],  # 不再替换换行符，保留原始Markdown
            "created_at": issue["created_at"],
            "updated_at": issue["updated_at"]
        }
    except Exception as e:
        print(f"⚠️ 获取 Issue 内容失败：{str(e)}")
        return None

def generate_pagination_data(posts, current_page):
    """生成分页数据"""
    total_posts = len(posts)
    total_pages = max(1, (total_posts + PER_PAGE - 1) // PER_PAGE)  # 总页数
    
    # 确保当前页在有效范围内
    current_page = max(1, min(current_page, total_pages))
    
    # 计算当前页显示的文章
    start = (current_page - 1) * PER_PAGE
    end = start + PER_PAGE
    current_posts = posts[start:end]
    
    # 计算上一页和下一页的URL
    prev_url = f"index_{current_page - 1}.html" if current_page > 1 else None
    next_url = f"index_{current_page + 1}.html" if current_page < total_pages else None
    
    return {
        "current_page": current_page,
        "total_pages": total_pages,
        "prev_url": prev_url,
        "next_url": next_url,
        "current_posts": current_posts
    }

def generate_html(blog_base, issue_content=None):
    """生成带分页和Markdown支持的HTML博客页面"""
    # 1. 更新博客基础信息
    blog_base["last_update"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    # 2. 如果有Issue内容，添加为新文章
    if issue_content and isinstance(blog_base["posts"], list):
        new_post = {
            "id": len(blog_base["posts"]) + 1,
            "title": issue_content["title"],
            "content": issue_content["content"],  # 保留原始Markdown内容
            "created_at": issue_content["created_at"].split("T")[0],
            "updated_at": issue_content["updated_at"].split("T")[0]
        }
        blog_base["posts"].append(new_post)
        # 保存更新后的blogBase.json
        with open(BLOG_BASE_FILE, "w", encoding="utf-8") as f:
            json.dump(blog_base, f, ensure_ascii=False, indent=2)
        print(f"✅ 新增文章：{issue_content['title']}")
    
    # 准备文章列表（倒序，最新的在前）
    posts = list(reversed(blog_base["posts"]))
    total_pages = max(1, (len(posts) + PER_PAGE - 1) // PER_PAGE)
    
    # 3. 生成所有分页页面（包含Markdown解析支持）
    html_template = """
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <!-- 引入Markdown解析库和代码高亮库 -->
    <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/highlight.js@11.7.0/lib/highlight.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/highlight.js@11.7.0/styles/github.min.css">
    <style>
        body {{ max-width: 1200px; margin: 0 auto; padding: 20px; font-family: Arial, sans-serif; }}
        .header {{ text-align: center; margin-bottom: 50px; }}
        .post {{ margin: 30px 0; padding: 20px; border-bottom: 1px solid #eee; }}
        .post-title {{ color: #2c3e50; margin-bottom: 10px; }}
        .post-meta {{ color: #7f8c8d; font-size: 0.9em; margin-bottom: 15px; }}
        .post-content {{ line-height: 1.6; color: #34495e; }}
        .footer {{ text-align: center; margin-top: 50px; color: #7f8c8d; }}
        .no-posts {{ text-align: center; padding: 50px; color: #7f8c8d; }}
        .pagination {{ text-align: center; margin: 30px 0; }}
        .pagination a {{ 
            display: inline-block; 
            margin: 0 5px; 
            padding: 8px 16px; 
            text-decoration: none; 
            border: 1px solid #ddd; 
            color: #333;
            border-radius: 4px;
        }}
        .pagination a.active {{ 
            background-color: #4CAF50; 
            color: white; 
            border: 1px solid #4CAF50;
        }}
        .pagination a:hover:not(.active) {{ background-color: #ddd; }}
        .pagination a.disabled {{
            opacity: 0.5;
            pointer-events: none;
            background-color: #f1f1f1;
        }}
        /* Markdown样式增强 */
        .post-content h1 {{ font-size: 1.8em; margin: 1.5em 0 1em; }}
        .post-content h2 {{ font-size: 1.5em; margin: 1.2em 0 0.8em; }}
        .post-content h3 {{ font-size: 1.2em; margin: 1em 0 0.6em; }}
        .post-content ul, .post-content ol {{ margin: 1em 0; padding-left: 2em; }}
        .post-content li {{ margin: 0.5em 0; }}
        .post-content p {{ margin: 1em 0; }}
        .post-content blockquote {{ 
            border-left: 4px solid #ddd; 
            padding-left: 1em; 
            margin: 1em 0; 
            color: #666;
        }}
        .post-content code {{ 
            background: #f5f5f5; 
            padding: 0.2em 0.4em; 
            border-radius: 4px;
            font-family: monospace;
        }}
        .post-content pre {{ 
            background: #f5f5f5; 
            padding: 1em; 
            border-radius: 4px;
            overflow-x: auto;
            margin: 1em 0;
        }}
        .post-content pre code {{ 
            padding: 0;
            background: none;
        }}
        .post-content a {{ color: #2c3e50; text-decoration: underline; }}
        .post-content img {{ max-width: 100%; margin: 1em 0; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>{title}</h1>
        <p>{subtitle}</p>
        <p>作者：{author} | 最后更新：{last_update}</p>
    </div>

    <div class="posts">
        {posts_html}
    </div>

    <div class="pagination">
        {pagination_html}
    </div>

    <div class="footer">
        <p>数字的世界 | <a href="https://ruihan.xin" target="_blank">数字森林</a></p>
    </div>

    <script>
        // 页面加载完成后解析所有Markdown内容
        document.addEventListener('DOMContentLoaded', function() {{
            // 解析文章内容
            document.querySelectorAll('.post-content').forEach(function(element) {{
                const markdown = element.textContent;
                const html = marked.parse(markdown);
                element.innerHTML = html;
            }});
            
            // 代码高亮处理
            document.querySelectorAll('pre code').forEach(function(block) {{
                hljs.highlightElement(block);
            }});
        }});
    </script>
</body>
</html>
    """
    
    # 为每一页生成HTML
    for page in range(1, total_pages + 1):
        pagination = generate_pagination_data(posts, page)
        
        # 生成文章列表HTML（保留原始Markdown内容用于前端解析）
        if pagination["current_posts"]:
            posts_html = ""
            for post in pagination["current_posts"]:
                posts_html += f"""
                <div class="post">
                    <h2 class="post-title">{post['title']}</h2>
                    <div class="post-meta">创建时间：{post['created_at']} | 更新时间：{post['updated_at']}</div>
                    <div class="post-content">{post['content']}</div>
                </div>
                """
        else:
            posts_html = '<div class="no-posts">暂无文章，快去创建 Issue 生成第一篇博客吧！</div>'
        
        # 生成分页按钮HTML
        pagination_html = []
        # 上一页
        if pagination["prev_url"]:
            pagination_html.append(f'<a href="{pagination["prev_url"]}">上一页</a>')
        else:
            pagination_html.append('<a class="disabled">上一页</a>')
        
        # 页码
        for i in range(1, total_pages + 1):
            if i == pagination["current_page"]:
                pagination_html.append(f'<a href="index_{i}.html" class="active">{i}</a>')
            else:
                pagination_html.append(f'<a href="index_{i}.html">{i}</a>')
        
        # 下一页
        if pagination["next_url"]:
            pagination_html.append(f'<a href="{pagination["next_url"]}">下一页</a>')
        else:
            pagination_html.append('<a class="disabled">下一页</a>')
        
        pagination_html = "".join(pagination_html)
        
        # 填充模板
        index_html = html_template.format(
            title=blog_base["title"],
            subtitle=blog_base["subtitle"],
            author=blog_base["author"],
            last_update=blog_base["last_update"],
            posts_html=posts_html,
            pagination_html=pagination_html
        )
        
        # 保存页面（首页同时保存为index.html方便访问）
        if page == 1:
            index_paths = [
                os.path.join(DOCS_DIR, "index.html"),
                os.path.join(DOCS_DIR, f"index_{page}.html")
            ]
        else:
            index_paths = [os.path.join(DOCS_DIR, f"index_{page}.html")]
        
        for path in index_paths:
            with open(path, "w", encoding="utf-8") as f:
                f.write(index_html)
            print(f"✅ 生成页面：{path}")

def backup_blog_base():
    """备份 blogBase.json 到 backup 目录"""
    if os.path.exists(BLOG_BASE_FILE):
        backup_path = os.path.join(BACKUP_DIR, f"blogBase_{datetime.now().strftime('%Y%m%d%H%M%S')}.json")
        with open(BLOG_BASE_FILE, "r", encoding="utf-8") as f_in, open(backup_path, "w", encoding="utf-8") as f_out:
            json.dump(json.load(f_in), f_out, ensure_ascii=False, indent=2)
        print(f"✅ 备份配置文件：{backup_path}")

def main():
    # 解析命令行参数
    parser = argparse.ArgumentParser(description="Gmeek Blog Generator")
    parser.add_argument("github_token", help="GitHub Token for API access")
    parser.add_argument("repo", help="GitHub Repository (owner/repo)")
    parser.add_argument("--issue_number", help="GitHub Issue Number to fetch content", default="")
    args = parser.parse_args()
    
    try:
        print("🚀 开始执行 Gmeek 博客生成流程...")
        # 1. 初始化目录
        init_dirs()
        # 2. 加载博客基础配置
        blog_base = load_blog_base()
        # 3. （可选）从Issue获取内容
        issue_content = fetch_issue_content(args.github_token, args.repo, args.issue_number)
        # 4. 生成HTML页面（带分页和Markdown支持）
        generate_html(blog_base, issue_content)
        # 5. 备份配置文件
        backup_blog_base()
        print("🎉 Gmeek 博客生成流程执行完成！")
    except Exception as e:
        print(f"❌ 执行失败：{str(e)}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

if __name__ == "__main__":
    main()
